### ISSUE TITLE
Any support for newer versions?

### ISSUE THREAD

**Issue by pnill** [Michidu/ILUnpacker#1]
Seems to fail when attempting to unpack something at
https://github.com/Michidu/ILUnpacker/blob/master/ILUnpacker/Program.cs#L107

methodDelegate is null.

**Comment by pnill** [comment]
The app version I have is newer 2.0.21.9 I'm guessing that's why It didn't work.

**Comment by pnill** [comment]
https://github.com/RexProg/ILProtectorUnpacker/blob/master/ILProtectorUnpacker.cs

Seems to have gotten his code from you, I'm wondering if you could help explain why the native invoke function within the application is returning null instead of returning the method of the idx being supplied.

I've opened an issue on his git as well, but I suspect since he seems to have learned how this works from you; he may not know what's wrong here.

**Comment by Michidu** [comment]
Answered on T4Y.
